version: '3'

services:

  db:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=arqsoft

  tomcat:
    build: .
    volumes:
      - ./target/test.war:/usr/local/tomcat/webapps/ROOT.war
      - ./target/test:/usr/local/tomcat/webapps/ROOT
    depends_on:
      - db
    ports:
      - "8000:8080"
